# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShoreDataCollector
                                 A QGIS plugin
 The tool collects recognized and refined shapes of water shore lines from satellite images and date lists
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-29
        copyright            : (C) 2024 by Evgeny Cherkashin and Oksana Mazayeva
        email                : eugeneai@irnok.net, moks@crust.irk.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShoreDataCollector class from file ShoreDataCollector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shore_qgis_plugin import ShoreDataCollector
    return ShoreDataCollector(iface)
